const events = [
  {
    _id: '6260f4c0af6ee336eb224a78',
    index: 0,
    isActive: true,
    ticketPrice: '$3,072.30',
    picture: '/images/events (1).jpg',
    eventTitle: 'Gena Owen.',
    organizedBy: 'KIDSTOCK',
    contactEmail: 'genaowen@kidstock.com',
    contactPhone: '+1 (972) 404-3941',
    location: '407 Jefferson Avenue, Hiwasse, Oklahoma, 9212',
    description:
      'Fugiat eu ut aliqua amet nisi cupidatat incididunt excepteur. Nostrud sunt nostrud duis sit non deserunt. Esse proident aliquip exercitation consectetur fugiat ipsum nostrud incididunt esse aliqua consequat deserunt et.\r\n',
    eventDate: 'Wed Aug 17 2022 23:31:09 GMT+0600 (Bangladesh Standard Time)',
    tags: ['sit', 'enim', 'do', 'minim', 'proident', 'non', 'qui'],
  },
  {
    _id: '6260f4c07129e2698f268a3f',
    index: 1,
    isActive: false,
    ticketPrice: '$3,278.54',
    picture: '/images/events (2).jpg',
    eventTitle: 'Rosales Sanford.',
    organizedBy: 'NAVIR',
    contactEmail: 'rosalessanford@navir.com',
    contactPhone: '+1 (895) 481-3463',
    location: '724 Strauss Street, Madrid, New York, 8207',
    description:
      'Voluptate nulla ut pariatur non mollit enim ad elit sunt pariatur velit incididunt est. Et reprehenderit ipsum exercitation aliqua laborum officia ullamco ut. Enim mollit enim adipisicing proident cupidatat et labore nisi dolor. Officia et dolore laborum reprehenderit cupidatat labore qui aliqua elit. Proident ipsum ut magna excepteur amet do eiusmod ipsum.\r\n',
    eventDate: 'Wed Sep 21 2022 17:58:20 GMT+0600 (Bangladesh Standard Time)',
    tags: ['nisi', 'ullamco', 'elit', 'minim', 'amet', 'commodo', 'amet'],
  },
  {
    _id: '6260f4c0c169ce7ea2fae988',
    index: 2,
    isActive: false,
    ticketPrice: '$2,535.93',
    picture: '/images/events (3).jpg',
    eventTitle: 'Britney Carey.',
    organizedBy: 'LYRICHORD',
    contactEmail: 'britneycarey@lyrichord.com',
    contactPhone: '+1 (977) 403-3056',
    location: '269 Melba Court, Coldiron, Alabama, 195',
    description:
      'Ex quis fugiat ex anim adipisicing. Irure excepteur occaecat esse magna. Eu consectetur deserunt pariatur incididunt ullamco elit labore irure labore et incididunt cupidatat proident.\r\n',
    eventDate: 'Sat Dec 17 2022 19:20:53 GMT+0600 (Bangladesh Standard Time)',
    tags: [
      'Lorem',
      'laborum',
      'velit',
      'consectetur',
      'proident',
      'magna',
      'adipisicing',
    ],
  },
  {
    _id: '6260f4c012e9cc4128417ae8',
    index: 3,
    isActive: false,
    ticketPrice: '$1,478.16',
    picture: '/images/events (4).jpg',
    eventTitle: 'Hicks Marshall.',
    organizedBy: 'INJOY',
    contactEmail: 'hicksmarshall@injoy.com',
    contactPhone: '+1 (859) 567-2298',
    location: '361 Ovington Court, Allensworth, District Of Columbia, 1389',
    description:
      'Laborum pariatur id adipisicing adipisicing ullamco reprehenderit Lorem laboris. Reprehenderit excepteur aute dolor non cupidatat velit ullamco reprehenderit voluptate. Duis sit nulla Lorem officia magna culpa pariatur exercitation. Duis eiusmod nulla sunt Lorem dolor. Ad mollit duis reprehenderit dolor amet incididunt nulla sunt mollit. Labore ullamco enim voluptate deserunt consequat enim tempor et. In anim aliqua tempor aliquip laboris ex.\r\n',
    eventDate: 'Fri Jan 21 2022 14:04:52 GMT+0600 (Bangladesh Standard Time)',
    tags: ['nisi', 'aliquip', 'occaecat', 'culpa', 'in', 'minim', 'officia'],
  },
  {
    _id: '6260f4c02b1b8f8f71ef8320',
    index: 4,
    isActive: false,
    ticketPrice: '$1,530.97',
    picture: '/images/events (5).jpg',
    eventTitle: 'Butler Levy.',
    organizedBy: 'SENMAO',
    contactEmail: 'butlerlevy@senmao.com',
    contactPhone: '+1 (999) 415-3378',
    location: '150 Bleecker Street, Roulette, Washington, 4724',
    description:
      'Nisi sit pariatur non nulla incididunt ullamco dolore consectetur minim incididunt pariatur non. Qui nisi minim voluptate mollit veniam duis. Ullamco veniam ex aliquip irure ad elit quis ea elit. Esse adipisicing laborum labore dolor ad non excepteur reprehenderit et aute. Velit esse dolore labore commodo proident minim in aute non nostrud ex.\r\n',
    eventDate: 'Thu Dec 29 2022 04:34:05 GMT+0600 (Bangladesh Standard Time)',
    tags: [
      'elit',
      'veniam',
      'cillum',
      'nostrud',
      'adipisicing',
      'ullamco',
      'qui',
    ],
  },
  {
    _id: '6260f4c09320c545f58aa40a',
    index: 5,
    isActive: true,
    ticketPrice: '$2,405.25',
    picture: '/images/events (6).jpg',
    eventTitle: 'Blanchard Mueller.',
    organizedBy: 'KOZGENE',
    contactEmail: 'blanchardmueller@kozgene.com',
    contactPhone: '+1 (915) 555-2187',
    location: '328 Withers Street, Worton, Utah, 8856',
    description:
      'Ea eiusmod et cillum pariatur esse ex anim est excepteur reprehenderit id. Id ullamco in minim laborum voluptate laboris eu elit laboris. Irure nostrud cillum qui consectetur sit duis incididunt adipisicing tempor pariatur elit dolore. Id exercitation eiusmod anim mollit sunt aute velit. Tempor consectetur eu eiusmod ea.\r\n',
    eventDate: 'Fri Apr 01 2022 07:44:44 GMT+0600 (Bangladesh Standard Time)',
    tags: ['ex', 'magna', 'culpa', 'elit', 'sunt', 'dolore', 'laborum'],
  },
  {
    _id: '6260f4c0d3f9d44dbe2627f7',
    index: 6,
    isActive: true,
    ticketPrice: '$3,426.74',
    picture: '/images/events (7).jpg',
    eventTitle: 'Figueroa Preston.',
    organizedBy: 'SPLINX',
    contactEmail: 'figueroapreston@splinx.com',
    contactPhone: '+1 (885) 513-2896',
    location: '627 Poly Place, Fannett, American Samoa, 8573',
    description:
      'Non non reprehenderit non incididunt. Voluptate veniam ad est voluptate sunt elit deserunt proident nostrud dolore pariatur. Quis qui dolore esse duis exercitation. Amet irure quis do culpa ad deserunt occaecat id. Fugiat reprehenderit eiusmod id occaecat eiusmod nulla est. Excepteur dolor consectetur esse sint laborum reprehenderit laboris adipisicing pariatur consequat et qui.\r\n',
    eventDate: 'Wed May 18 2022 13:06:14 GMT+0600 (Bangladesh Standard Time)',
    tags: ['officia', 'Lorem', 'magna', 'irure', 'quis', 'eiusmod', 'est'],
  },
  {
    _id: '6260f4c0c39cdc5d20da7a0a',
    index: 7,
    isActive: false,
    ticketPrice: '$1,096.10',
    picture: '/images/events (8).jpg',
    eventTitle: 'Tammy Richards.',
    organizedBy: 'EARTHMARK',
    contactEmail: 'tammyrichards@earthmark.com',
    contactPhone: '+1 (971) 416-3303',
    location: '932 Perry Place, Saddlebrooke, Montana, 6603',
    description:
      'Duis ad ut aute laboris ullamco officia incididunt laboris adipisicing anim aliqua amet culpa amet. Est deserunt minim voluptate in eiusmod nisi ad mollit. Aute ullamco culpa velit cillum officia aliquip duis labore quis deserunt. Ut officia consectetur qui incididunt ullamco occaecat.\r\n',
    eventDate: 'Sat Nov 05 2022 14:02:59 GMT+0600 (Bangladesh Standard Time)',
    tags: ['veniam', 'et', 'ad', 'sunt', 'fugiat', 'ex', 'tempor'],
  },
  {
    _id: '6260f4c00c9d781ffd45ddc5',
    index: 8,
    isActive: false,
    ticketPrice: '$1,311.08',
    picture: '/images/events (9).jpg',
    eventTitle: 'Carole Haney.',
    organizedBy: 'PORTALINE',
    contactEmail: 'carolehaney@portaline.com',
    contactPhone: '+1 (976) 403-2166',
    location: '193 Leonora Court, Guthrie, Vermont, 5611',
    description:
      'Cillum aliqua consectetur officia anim nulla id. Ullamco in nisi duis anim esse aliquip in. Pariatur veniam dolore enim enim est ullamco id irure officia quis do in anim.\r\n',
    eventDate: 'Sat Dec 24 2022 20:36:11 GMT+0600 (Bangladesh Standard Time)',
    tags: ['ex', 'minim', 'incididunt', 'anim', 'est', 'cillum', 'est'],
  },
  {
    _id: '6260f4c0631a3ed1acfa493f',
    index: 9,
    isActive: false,
    ticketPrice: '$2,534.56',
    picture: '/images/events (10).jpg',
    eventTitle: 'Long Bird.',
    organizedBy: 'XURBAN',
    contactEmail: 'longbird@xurban.com',
    contactPhone: '+1 (947) 418-2881',
    location: '683 Fleet Place, Welda, Virgin Islands, 119',
    description:
      'Pariatur do laborum do nostrud pariatur exercitation incididunt velit est irure. Cupidatat ullamco nisi adipisicing tempor aliqua non. Dolore non eu id anim quis reprehenderit in nostrud mollit ullamco ad.\r\n',
    eventDate: 'Thu Sep 01 2022 05:12:51 GMT+0600 (Bangladesh Standard Time)',
    tags: ['quis', 'sint', 'sint', 'sit', 'est', 'tempor', 'laboris'],
  },
  {
    _id: '6260f4c0ea2f346f50dc2a7a',
    index: 10,
    isActive: true,
    ticketPrice: '$2,972.95',
    picture: '/images/events (11).jpg',
    eventTitle: 'Valentine Watts.',
    organizedBy: 'KEEG',
    contactEmail: 'valentinewatts@keeg.com',
    contactPhone: '+1 (861) 567-3280',
    location: '355 Lafayette Avenue, Savannah, Guam, 4474',
    description:
      'Dolor nulla incididunt ex quis esse ad aliqua velit magna cillum irure mollit ipsum ullamco. Non commodo sint ex non nulla ipsum magna do dolore non aliquip sint dolore dolore. Amet esse culpa aliqua ut. Deserunt labore aliquip quis esse exercitation exercitation laborum ad id magna.\r\n',
    eventDate: 'Wed Feb 02 2022 05:01:02 GMT+0600 (Bangladesh Standard Time)',
    tags: ['fugiat', 'labore', 'eu', 'id', 'anim', 'sit', 'voluptate'],
  },
  {
    _id: '6260f4c0ba477b2f924d2ce3',
    index: 11,
    isActive: false,
    ticketPrice: '$1,818.37',
    picture: '/images/events (12).jpg',
    eventTitle: 'Rebecca Holloway.',
    organizedBy: 'COMSTAR',
    contactEmail: 'rebeccaholloway@comstar.com',
    contactPhone: '+1 (822) 530-2716',
    location: '192 Berkeley Place, Aberdeen, South Carolina, 4727',
    description:
      'Culpa elit anim mollit irure quis. Aliqua esse quis sit laboris Lorem non pariatur quis occaecat. Sit enim Lorem ad aliquip incididunt aliquip commodo pariatur magna nisi proident minim aute exercitation. Nostrud do nostrud consectetur reprehenderit nostrud. Nostrud nostrud pariatur sunt aliquip proident sit laborum fugiat amet occaecat consectetur aliquip tempor. Qui anim in irure laboris. Consectetur aute consequat aliquip in adipisicing proident culpa est consectetur ea non nostrud.\r\n',
    eventDate: 'Thu Jan 13 2022 10:00:30 GMT+0600 (Bangladesh Standard Time)',
    tags: [
      'deserunt',
      'pariatur',
      'minim',
      'labore',
      'commodo',
      'labore',
      'culpa',
    ],
  },
  {
    _id: '6260f4c0bb38c32209485b05',
    index: 12,
    isActive: true,
    ticketPrice: '$3,346.64',
    picture: '/images/events (13).jpg',
    eventTitle: 'Mari Odonnell.',
    organizedBy: 'HOMETOWN',
    contactEmail: 'mariodonnell@hometown.com',
    contactPhone: '+1 (950) 583-2674',
    location: '180 Wolf Place, Hayes, Northern Mariana Islands, 2143',
    description:
      'Aliquip quis quis incididunt ipsum exercitation ea Lorem eiusmod ipsum consequat tempor. Adipisicing quis veniam est voluptate deserunt id ipsum consectetur ullamco ullamco. Pariatur tempor ex exercitation voluptate labore irure culpa labore officia sint proident. Labore aliqua excepteur aliquip dolore anim aliquip magna mollit officia minim commodo ut sit. Aliquip minim excepteur officia exercitation. Deserunt in ipsum sint ad irure elit esse amet nisi duis in duis nostrud aute. Sint labore et minim non minim tempor labore nulla do.\r\n',
    eventDate: 'Wed Dec 14 2022 12:45:22 GMT+0600 (Bangladesh Standard Time)',
    tags: ['ipsum', 'esse', 'sint', 'laboris', 'excepteur', 'fugiat', 'labore'],
  },
  {
    _id: '6260f4c00cba7d8e9834c5e7',
    index: 13,
    isActive: true,
    ticketPrice: '$3,771.22',
    picture: '/images/events (14).jpg',
    eventTitle: 'Cynthia Witt.',
    organizedBy: 'PODUNK',
    contactEmail: 'cynthiawitt@podunk.com',
    contactPhone: '+1 (894) 488-2689',
    location: '205 Heyward Street, Elliston, North Dakota, 3773',
    description:
      'Nisi esse excepteur est ut deserunt exercitation velit voluptate incididunt excepteur. Reprehenderit velit magna non elit magna nisi dolor proident laborum ad aliquip. Laboris aute nostrud aliqua esse cupidatat id dolor enim commodo ullamco non. Minim voluptate ad voluptate in proident.\r\n',
    eventDate: 'Sat May 07 2022 05:28:25 GMT+0600 (Bangladesh Standard Time)',
    tags: ['tempor', 'et', 'anim', 'aliqua', 'est', 'sint', 'irure'],
  },
  {
    _id: '6260f4c08ec137a541129c12',
    index: 14,
    isActive: true,
    ticketPrice: '$2,592.31',
    picture: '/images/events (15).jpg',
    eventTitle: 'Brown Mcdonald.',
    organizedBy: 'MOLTONIC',
    contactEmail: 'brownmcdonald@moltonic.com',
    contactPhone: '+1 (950) 568-2923',
    location: '741 Florence Avenue, Wescosville, Arkansas, 2575',
    description:
      'Velit eu reprehenderit cupidatat ea id amet. Aliquip amet deserunt labore est pariatur et. Exercitation non est nostrud aliqua cupidatat laborum duis. Ad sint voluptate eiusmod et Lorem irure ipsum.\r\n',
    eventDate: 'Sun May 01 2022 07:48:42 GMT+0600 (Bangladesh Standard Time)',
    tags: [
      'proident',
      'incididunt',
      'laborum',
      'eu',
      'occaecat',
      'irure',
      'aliqua',
    ],
  },
  {
    _id: '6260f4c012215a59c2c12eec',
    index: 15,
    isActive: false,
    ticketPrice: '$1,659.15',
    picture: '/images/events (16).jpg',
    eventTitle: 'Rosemarie Davidson.',
    organizedBy: 'ZEROLOGY',
    contactEmail: 'rosemariedavidson@zerology.com',
    contactPhone: '+1 (920) 476-3394',
    location: '263 Hall Street, Corinne, South Dakota, 6456',
    description:
      'Nisi ipsum exercitation deserunt qui eu sunt dolor nisi ipsum non labore reprehenderit. Tempor proident Lorem irure non adipisicing non pariatur anim adipisicing labore. Laboris ad consectetur Lorem Lorem consequat consectetur amet. Sint proident anim deserunt eu. Nisi elit reprehenderit dolore anim sint culpa incididunt minim. Sit ad et commodo ex consequat velit do amet amet ut sint ullamco.\r\n',
    eventDate: 'Wed Feb 23 2022 17:32:40 GMT+0600 (Bangladesh Standard Time)',
    tags: [
      'duis',
      'nisi',
      'consectetur',
      'laborum',
      'dolor',
      'reprehenderit',
      'magna',
    ],
  },
  {
    _id: '6260f4c0c6ef2de6353c85a3',
    index: 16,
    isActive: true,
    ticketPrice: '$3,478.51',
    picture: '/images/events (17).jpg',
    eventTitle: 'Hilda Bauer.',
    organizedBy: 'COMVOY',
    contactEmail: 'hildabauer@comvoy.com',
    contactPhone: '+1 (910) 436-2026',
    location: '209 Ridgewood Place, Harold, Maryland, 5050',
    description:
      'Proident minim sint incididunt adipisicing sunt in nostrud. Voluptate duis eiusmod dolor magna. Ut eu ad aliqua non voluptate excepteur consectetur consectetur mollit. Sit in minim ipsum officia.\r\n',
    eventDate: 'Fri Nov 18 2022 22:27:53 GMT+0600 (Bangladesh Standard Time)',
    tags: ['consequat', 'veniam', 'nulla', 'aute', 'sunt', 'est', 'ea'],
  },
  {
    _id: '6260f4c01065e1c0023e639a',
    index: 17,
    isActive: true,
    ticketPrice: '$2,404.97',
    picture: '/images/events (18).jpg',
    eventTitle: 'Sanford Mckee.',
    organizedBy: 'ACCUPRINT',
    contactEmail: 'sanfordmckee@accuprint.com',
    contactPhone: '+1 (828) 550-3054',
    location: '457 Perry Terrace, Riceville, Mississippi, 4603',
    description:
      'Sint enim qui irure fugiat eu consectetur. Culpa aute sint consectetur amet ad do officia cupidatat. Ea cillum labore ullamco occaecat occaecat aute irure sit id deserunt do. Officia fugiat consectetur amet non ea magna magna sit.\r\n',
    eventDate: 'Wed May 18 2022 05:46:59 GMT+0600 (Bangladesh Standard Time)',
    tags: ['veniam', 'et', 'enim', 'adipisicing', 'nostrud', 'commodo', 'nisi'],
  },
  {
    _id: '6260f4c034e779c871dafe2e',
    index: 18,
    isActive: false,
    ticketPrice: '$2,862.94',
    picture: '/images/events (19).jpg',
    eventTitle: 'Richards Mclean.',
    organizedBy: 'PLUTORQUE',
    contactEmail: 'richardsmclean@plutorque.com',
    contactPhone: '+1 (982) 594-2209',
    location: '228 Lombardy Street, Graball, Maine, 4860',
    description:
      'Laboris ipsum aute occaecat sit incididunt reprehenderit deserunt mollit fugiat labore ea. Amet cupidatat eu exercitation consectetur minim mollit sint eiusmod. Mollit voluptate cillum excepteur eu enim eu non mollit irure pariatur id adipisicing quis ex. Duis non elit duis nulla culpa deserunt nostrud cillum sunt ex duis. Elit est dolor id adipisicing labore. Sunt consectetur consectetur et aliquip ad. Adipisicing aliquip consequat consequat excepteur dolore ex laborum dolore veniam consequat minim.\r\n',
    eventDate: 'Wed Feb 09 2022 08:00:53 GMT+0600 (Bangladesh Standard Time)',
    tags: ['id', 'nostrud', 'et', 'adipisicing', 'sit', 'ipsum', 'voluptate'],
  },
  {
    _id: '6260f4c0f0f9d31aab2d83e1',
    index: 19,
    isActive: true,
    ticketPrice: '$2,699.30',
    picture: '/images/events (20).jpg',
    eventTitle: 'Mavis Russell.',
    organizedBy: 'KATAKANA',
    contactEmail: 'mavisrussell@katakana.com',
    contactPhone: '+1 (803) 592-2756',
    location: '731 Conselyea Street, Finzel, Illinois, 2718',
    description:
      'Incididunt ex in id occaecat sunt excepteur aute cillum non magna. Eu tempor esse laboris laborum id esse est ea sint id ea enim adipisicing. Deserunt esse irure ipsum elit. Reprehenderit dolor ex laboris occaecat enim enim nostrud. Dolore cillum non id commodo fugiat ut excepteur aliqua cupidatat ut. Exercitation veniam laboris cupidatat ipsum velit occaecat officia aliqua dolor esse quis proident. Enim velit sint amet labore nulla fugiat anim eu voluptate irure.\r\n',
    eventDate: 'Fri Feb 11 2022 20:06:07 GMT+0600 (Bangladesh Standard Time)',
    tags: [
      'ipsum',
      'sint',
      'dolore',
      'excepteur',
      'anim',
      'eu',
      'exercitation',
    ],
  },
  {
    _id: '6260f4c0fd80368fd0ce487c',
    index: 20,
    isActive: false,
    ticketPrice: '$3,890.25',
    picture: '/images/events (21).jpg',
    eventTitle: 'Albert White.',
    organizedBy: 'ECRATIC',
    contactEmail: 'albertwhite@ecratic.com',
    contactPhone: '+1 (942) 442-3144',
    location: '791 Prospect Place, Jacumba, Nevada, 4894',
    description:
      'Lorem et ipsum dolor sint aliquip id nulla laborum exercitation ut proident. Ex anim culpa do amet aute deserunt laboris aliquip qui minim incididunt. Consequat esse eiusmod esse id laborum aute. Ad nulla minim aliqua labore voluptate. Excepteur commodo tempor culpa eu do. Ad deserunt laborum commodo nisi. Cupidatat ullamco elit commodo laboris consequat commodo duis commodo sunt dolore.\r\n',
    eventDate: 'Wed Aug 31 2022 21:04:40 GMT+0600 (Bangladesh Standard Time)',
    tags: [
      'cupidatat',
      'consequat',
      'voluptate',
      'laborum',
      'fugiat',
      'minim',
      'excepteur',
    ],
  },
  {
    _id: '6260f4c0b420eabffc319dc9',
    index: 21,
    isActive: true,
    ticketPrice: '$1,673.03',
    picture: '/images/events (22).jpg',
    eventTitle: 'Debbie Jones.',
    organizedBy: 'HARMONEY',
    contactEmail: 'debbiejones@harmoney.com',
    contactPhone: '+1 (941) 472-3599',
    location: '133 Dekoven Court, Mulberry, Louisiana, 2274',
    description:
      'Labore veniam magna et commodo. In aute dolor elit quis cillum deserunt ipsum esse est excepteur aute minim consequat occaecat. Aliquip ea deserunt et labore velit eu veniam occaecat adipisicing occaecat pariatur. Ipsum laboris minim quis consectetur culpa enim est fugiat mollit officia ipsum aliquip. Anim nostrud aliquip duis laborum velit ea incididunt amet ipsum eu anim aliquip. Proident aliqua in Lorem ad. Et eu ullamco exercitation occaecat proident fugiat duis ipsum cillum.\r\n',
    eventDate: 'Fri Jul 29 2022 09:03:33 GMT+0600 (Bangladesh Standard Time)',
    tags: [
      'magna',
      'et',
      'pariatur',
      'culpa',
      'mollit',
      'excepteur',
      'adipisicing',
    ],
  },
  {
    _id: '6260f4c0757b32ce890e30be',
    index: 22,
    isActive: false,
    ticketPrice: '$1,663.69',
    picture: '/images/events (23).jpg',
    eventTitle: 'Carmella Macias.',
    organizedBy: 'XIXAN',
    contactEmail: 'carmellamacias@xixan.com',
    contactPhone: '+1 (810) 591-3815',
    location: '287 Alice Court, Taycheedah, Florida, 944',
    description:
      'Consectetur aliqua est velit amet do commodo elit. Amet ut sit qui laboris labore nisi amet do. Ad id occaecat id non. Consectetur enim elit cillum ullamco commodo tempor. Laboris laboris ut id laboris adipisicing exercitation deserunt ad ea fugiat quis Lorem pariatur ex. Laborum ullamco est id deserunt sint ipsum exercitation anim culpa enim sunt do do eiusmod.\r\n',
    eventDate: 'Sun Aug 07 2022 06:46:10 GMT+0600 (Bangladesh Standard Time)',
    tags: ['labore', 'do', 'aliqua', 'labore', 'veniam', 'tempor', 'mollit'],
  },
  {
    _id: '6260f4c0a197181a50dbed19',
    index: 23,
    isActive: false,
    ticketPrice: '$1,555.14',
    picture: '/images/events (24).jpg',
    eventTitle: 'Cara Mercer.',
    organizedBy: 'DOGTOWN',
    contactEmail: 'caramercer@dogtown.com',
    contactPhone: '+1 (898) 577-3113',
    location: '532 Central Avenue, Bendon, Rhode Island, 5724',
    description:
      'Dolor et consectetur est aliqua ut consequat eu excepteur aliqua dolor. Sunt veniam quis nulla tempor elit aute. Lorem laborum duis sunt esse incididunt adipisicing fugiat mollit consequat velit esse.\r\n',
    eventDate: 'Thu Mar 31 2022 10:46:23 GMT+0600 (Bangladesh Standard Time)',
    tags: ['do', 'labore', 'nisi', 'exercitation', 'tempor', 'non', 'eiusmod'],
  },
  {
    _id: '6260f4c0a2279053b116d664',
    index: 24,
    isActive: true,
    ticketPrice: '$2,213.96',
    picture: '/images/events (25).jpg',
    eventTitle: 'Lelia Bass.',
    organizedBy: 'TRIPSCH',
    contactEmail: 'leliabass@tripsch.com',
    contactPhone: '+1 (918) 462-3270',
    location: '864 Ivan Court, Zortman, Virginia, 9739',
    description:
      'Ad in velit nulla sint sunt esse amet amet irure est magna veniam. Ut in commodo sunt incididunt eiusmod cupidatat irure tempor esse minim consectetur. Exercitation est minim eu quis dolore sunt ipsum ullamco. Aute labore deserunt tempor voluptate cillum. Quis dolore irure ullamco cillum.\r\n',
    eventDate: 'Mon Mar 14 2022 20:40:22 GMT+0600 (Bangladesh Standard Time)',
    tags: [
      'excepteur',
      'exercitation',
      'adipisicing',
      'occaecat',
      'ut',
      'excepteur',
      'aliquip',
    ],
  },
  {
    _id: '6260f4c0d39fee3349e69c20',
    index: 25,
    isActive: false,
    ticketPrice: '$2,781.76',
    picture: '/images/events (26).jpg',
    eventTitle: 'Maxine Potter.',
    organizedBy: 'GAPTEC',
    contactEmail: 'maxinepotter@gaptec.com',
    contactPhone: '+1 (945) 478-3158',
    location: '100 Rockwell Place, Hamilton, Ohio, 9905',
    description:
      'Fugiat adipisicing ipsum duis reprehenderit Lorem anim sit. Aliquip laboris ea qui culpa id minim. Consectetur ea deserunt et dolore consequat. Mollit adipisicing amet anim anim pariatur aliqua sit ullamco aute. Reprehenderit veniam nostrud proident ullamco ad enim sunt cupidatat dolor laboris duis. Sunt ea esse dolor Lorem non aliquip do irure nulla excepteur. Ad Lorem aute enim cillum.\r\n',
    eventDate: 'Tue Jan 18 2022 20:56:32 GMT+0600 (Bangladesh Standard Time)',
    tags: ['magna', 'ex', 'non', 'et', 'aliquip', 'voluptate', 'nisi'],
  },
  {
    _id: '6260f4c00e104682807bc794',
    index: 26,
    isActive: true,
    ticketPrice: '$3,255.10',
    picture: '/images/events (27).jpg',
    eventTitle: 'Alexandria Dickson.',
    organizedBy: 'FLOTONIC',
    contactEmail: 'alexandriadickson@flotonic.com',
    contactPhone: '+1 (970) 462-3582',
    location: '196 Himrod Street, Williston, Palau, 2572',
    description:
      'Pariatur laborum nostrud nostrud nostrud exercitation laborum voluptate culpa duis. Et aliquip ullamco anim nulla reprehenderit incididunt ea dolor labore. Irure enim commodo quis amet qui occaecat consectetur deserunt deserunt labore.\r\n',
    eventDate: 'Tue Aug 16 2022 10:43:31 GMT+0600 (Bangladesh Standard Time)',
    tags: ['ipsum', 'aute', 'Lorem', 'laborum', 'laboris', 'aliquip', 'ad'],
  },
  {
    _id: '6260f4c0825674319283d4ba',
    index: 27,
    isActive: false,
    ticketPrice: '$1,552.94',
    picture: '/images/events (28).jpg',
    eventTitle: 'Marisa Good.',
    organizedBy: 'ZENTURY',
    contactEmail: 'marisagood@zentury.com',
    contactPhone: '+1 (896) 565-2000',
    location: '565 Miller Avenue, Belgreen, Alaska, 8828',
    description:
      'Commodo qui esse minim id proident magna. Eu enim nostrud officia adipisicing minim sint adipisicing laborum magna ullamco voluptate ut reprehenderit. Veniam ullamco duis quis ut consectetur sit exercitation commodo sunt. Pariatur Lorem mollit officia reprehenderit ut.\r\n',
    eventDate: 'Fri Nov 11 2022 05:44:14 GMT+0600 (Bangladesh Standard Time)',
    tags: [
      'non',
      'sunt',
      'excepteur',
      'eu',
      'fugiat',
      'exercitation',
      'eiusmod',
    ],
  },
  {
    _id: '6260f4c0c78995ec67493616',
    index: 28,
    isActive: false,
    ticketPrice: '$1,377.52',
    picture: '/images/events (29).jpg',
    eventTitle: 'Nora Barton.',
    organizedBy: 'INCUBUS',
    contactEmail: 'norabarton@incubus.com',
    contactPhone: '+1 (943) 540-3538',
    location: '745 Schweikerts Walk, Westwood, Wyoming, 5341',
    description:
      'Laboris ea ullamco id et. Duis ex anim officia commodo qui eiusmod aliqua irure. Fugiat culpa in culpa cupidatat dolore ipsum ad commodo et sit qui reprehenderit. Nostrud sit ullamco Lorem ea ex voluptate do velit labore.\r\n',
    eventDate: 'Wed Mar 09 2022 22:28:34 GMT+0600 (Bangladesh Standard Time)',
    tags: ['reprehenderit', 'ipsum', 'Lorem', 'duis', 'do', 'et', 'incididunt'],
  },
  {
    _id: '6260f4c00e533b9f529e271e',
    index: 29,
    isActive: false,
    ticketPrice: '$1,437.71',
    picture: '/images/events (30).jpg',
    eventTitle: 'Briggs Benton.',
    organizedBy: 'ZILENCIO',
    contactEmail: 'briggsbenton@zilencio.com',
    contactPhone: '+1 (800) 472-3837',
    location: '283 Pineapple Street, Tuttle, Arizona, 7823',
    description:
      'Incididunt aliqua ex cupidatat quis sit minim nulla deserunt occaecat ut consectetur. Est veniam aliqua laborum cillum irure. Nostrud in est eiusmod adipisicing velit est laboris. Velit aute veniam enim nostrud nisi ullamco do mollit ipsum sint tempor velit laboris.\r\n',
    eventDate: 'Sun Mar 20 2022 11:55:51 GMT+0600 (Bangladesh Standard Time)',
    tags: ['ea', 'qui', 'est', 'exercitation', 'enim', 'est', 'magna'],
  },
  {
    _id: '6260f4c0975e6c6dc905ba7a',
    index: 30,
    isActive: true,
    ticketPrice: '$2,904.71',
    picture: '/images/events (31).jpg',
    eventTitle: 'Carson Ball.',
    organizedBy: 'COMTOURS',
    contactEmail: 'carsonball@comtours.com',
    contactPhone: '+1 (812) 496-2349',
    location: '848 Crooke Avenue, Lutsen, Puerto Rico, 9088',
    description:
      'Aliqua incididunt occaecat dolore nostrud nostrud cupidatat. Enim dolore incididunt consequat dolor consectetur do nostrud anim esse et pariatur. Id esse ullamco elit aliqua eu do nisi consequat magna sit dolore sint. Ullamco cupidatat voluptate elit nostrud voluptate quis.\r\n',
    eventDate: 'Wed Apr 13 2022 18:08:27 GMT+0600 (Bangladesh Standard Time)',
    tags: ['labore', 'ex', 'cupidatat', 'ex', 'dolore', 'sunt', 'tempor'],
  },
  {
    _id: '6260f4c0160e496e2ee6f0fe',
    index: 31,
    isActive: true,
    ticketPrice: '$3,348.40',
    picture: '/images/events (32).jpg',
    eventTitle: 'Hale Bryant.',
    organizedBy: 'MATRIXITY',
    contactEmail: 'halebryant@matrixity.com',
    contactPhone: '+1 (980) 527-2905',
    location: '817 Louise Terrace, Cade, New Jersey, 5199',
    description:
      'Reprehenderit id voluptate dolore et cillum. Voluptate commodo Lorem dolore cupidatat anim pariatur aliquip ex exercitation in consectetur. Exercitation velit dolore esse aliqua. Do irure cillum fugiat culpa exercitation amet sit. Elit non officia ea irure proident magna qui non magna consequat pariatur eu. Reprehenderit pariatur irure minim exercitation pariatur quis aute magna in enim amet pariatur irure ut.\r\n',
    eventDate: 'Wed Feb 23 2022 01:30:40 GMT+0600 (Bangladesh Standard Time)',
    tags: ['sint', 'officia', 'consectetur', 'culpa', 'sint', 'ea', 'ex'],
  },
  {
    _id: '6260f4c04083076d61b3bff8',
    index: 32,
    isActive: true,
    ticketPrice: '$3,172.54',
    picture: '/images/events (33).jpg',
    eventTitle: 'Bridget Goff.',
    organizedBy: 'ZENTILITY',
    contactEmail: 'bridgetgoff@zentility.com',
    contactPhone: '+1 (825) 507-3722',
    location: '291 Beard Street, Oneida, Federated States Of Micronesia, 4759',
    description:
      'Excepteur cillum proident enim pariatur ea ut sunt non fugiat cupidatat est Lorem. Dolor minim laboris enim occaecat tempor dolor. Nostrud excepteur dolor nostrud fugiat commodo consectetur quis. Laborum duis irure labore voluptate amet esse incididunt laborum non anim irure laborum.\r\n',
    eventDate: 'Tue Aug 02 2022 20:25:53 GMT+0600 (Bangladesh Standard Time)',
    tags: ['cupidatat', 'anim', 'veniam', 'cupidatat', 'enim', 'amet', 'minim'],
  },
];

export default events;
